### ISSUE TITLE
Status and updates

### ISSUE THREAD

**Issue by meesrutten** [petermekhaeil/nextjs-commerce-shopify#6]
Hi @petermekhaeil 👋

I was wondering if you are still actively working on this project?
If not, is it possible for you to create a wiki, projects or checklist of how it is possible to help finishing the project?

I'm really looking forward to using this for myself and my clients!

Thanks,
Mees

**Comment by petermekhaeil** [comment]
Hello! 

This project is production ready. I currently use it in production. The downside is that it requires you to make some heavy modifications to your Next.js Commerce application for it to work. The reason being is because this project was started as soon as Commerce was released, and I needed Shopify support at the time. Personally I will continue using this project in production as I use a modified version of Next.js Commerce.

Now that the Vercel team are working on adding additional providers such as Shopify, I have moved most of this code over to their project and they are going to continue the work: See the progress here: https://github.com/vercel/commerce/pull/186. They are working on making Shopify work without modifications to your Commerce application.

I suggest new users who want to use Spotify in Next.js Commerce without making changes, to follow the Vercel's teams progress. Otherwise, feel free to use this!

**Comment by staszewski** [comment]
Can you please share where i can find those envs https://github.com/vercel/commerce/pull/186/files#diff-6cbafeb55646fd9992540f76bb8961a69f6fe1ac5b017209b11957dfc3e5013cR37? I never used shopify before, i was googling it but couldn't find. Thanks.

**Comment by petermekhaeil** [comment]
> Can you please share where i can find those envs https://github.com/vercel/commerce/pull/186/files#diff-6cbafeb55646fd9992540f76bb8961a69f6fe1ac5b017209b11957dfc3e5013cR37? I never used shopify before, i was googling it but couldn't find. Thanks.

I recommend to read the instructions on Vercel's Commerce. They have instructions on how to switch providers:
https://github.com/vercel/commerce#how-to-change-providers.

The Vercel team has done a good job at adding on top of the Shopify provider and their implementation is well ahead of this repository. Best if you take follow their implementation and instructions on setting up Commerce with Shopify as a provider. Good luck!

**Comment by petermekhaeil** [comment]
Going to close this issue. Head over to [Vercel Commerce ](https://github.com/vercel/commerce) if you're building a Headless Commerce with Shopify. 👍
